language: objective-c
osx_image: xcode7
script:
- xcodebuild -project Examples/RDHCollectionViewTableLayoutDemo.xcodeproj -scheme RDHCollectionViewTableLayoutDemo -destination "platform=iOS Simulator,name=iPhone 6" clean build test